# Generated by Django 5.0.5 on 2024-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diseases'),
        ),
    ]
